### ISSUE TITLE
Outlook module extension appearing in mail instead of navigation bar

### ISSUE THREAD

**Issue by erazc** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#10]
Hi, 

I'm new to outlook add in development, I was trying to replicate this example but I'm facing some issues.

As per the screenshot shared in the project sample an icon should appear in the navigation bar but I cant find any icon on my navigation bar. 

Add in is appearing inside the mail.

![navbar](https://cloud.githubusercontent.com/assets/26617104/24233234/e8bad604-0fb6-11e7-8c45-a66350823830.png)

Navigation bar 

![mail](https://cloud.githubusercontent.com/assets/26617104/24233244/f5773ca2-0fb6-11e7-96ef-62be86a65c05.png)

Message box. 

Please help. Thanks.

**Comment by HamletHakobyan** [comment]
Hi, 

What is the version of you Outlook? As you know the module extentions available for Outlook 2016 only.

Regards

**Comment by erazc** [comment]
Hi, 

Thanks for the reply. I'm using Outlook 2016 only. Any idea why it is not coming ?

**Comment by chgowthami** [comment]
i too have a same issue

**Comment by yogendraemail** [comment]
i too have a same issue.

**Comment by samantharamon** [comment]
Please note that this sample has been archived is no longer actively maintained. For a more modern and convenient solution that will work across Microsoft 365 applications, we recommend checking out [personal tab apps that open in Outlook](https://learn.microsoft.com/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab).
