### ISSUE TITLE
Support for Outlook 2016 for Mac?

### ISSUE THREAD

**Issue by beders** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#12]
I'm not able to see any module level extension points in Outlook 2016 for Mac.
Are they supported?

**Comment by samantharamon** [comment]
Please note that this sample has been archived is no longer actively maintained. Module extensions are only supported in Outlook on Windows. For a more modern and convenient solution that will work across Microsoft 365 applications, we recommend checking out [personal tab apps that open in Outlook](https://learn.microsoft.com/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab).
