### ISSUE TITLE
ModuleExtension for outlook web

### ISSUE THREAD

**Issue by SPanwar06** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#13]
Does this module extension also support in outlook web. If not, is there is any other way to achieve the same.

**Comment by eblingus** [comment]
This module extension does not work with outlook web.

**Comment by samantharamon** [comment]
Please note that this sample has been archived is no longer actively maintained. Module extensions are only supported in Outlook on Windows. For a more modern and convenient solution that will work across Microsoft 365 applications, we recommend checking out [personal tab apps that open in Outlook](https://learn.microsoft.com/microsoftteams/platform/m365-apps/extend-m365-teams-personal-tab).
