### ISSUE TITLE
Provide manifest sample to support Add-in commands for Outlook 2016 build that do not support VersionOverridesV1_1

### ISSUE THREAD

**Issue by bpatra** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#2]
Hi,
it seems that some version of Outlook 2016 (e.g. 16.0.6568.2036) supports add-ins commands from `VersionOverridesV1_0`(e.g. `MessageReadCommandSurface`or `CustomPane`) but not the Modules from `VersionOverridesV1_1`.

In your sample, you put everything under a doubly nested VersionOverrides element

```
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides"
                    xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1"
                      xsi:type="VersionOverridesV1_1"> 
     <!-- Ressources, extension point  etc -->
  </VersionOverrides>
  </VersionOverrides>
```

The problem is that if you put existing extension points such as `MessageReadCommandSurface`or `CustomPane` Extension they got ignored from those Outlook 2016 not supporting the `VersionOverridesV1_1`

To solve this you have to duplicate the common material between elements `xsi:type="VersionOverridesV1_0"` and `xsi:type="VersionOverridesV1_1"`. It took me some time to figure it out and if you do not have access to such an Outlook build you may not be aware of the problem. It would be better to upgrade the manifest to add an "older" extension point so that people may see this pitfall.

Thank you

**Comment by chbighammsft** [comment]
Thanks for your suggestion. This sample is showing the simplest manifest file to implement the new “Module” extension point. The changes that you’re suggesting would make an excellent separate sample showing how to upgrade or integrate an existing add-in with the new extension point, but adding information about using other extension points to this sample would obscure the simple change that we’re illustrating.

**Comment by bpatra** [comment]
Hi,
I understand. We have implemented the module extension point for our new app, that is great. 
Thank you very much.
