### ISSUE TITLE
Office 365

### ISSUE THREAD

**Issue by JanBizub** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#5]
Hello. I tried installing this example on Office365.
But custom module doesnt appear.
Is this supported for o365 now?
If not, will module extension be supported for o365 later?

**Comment by chbighammsft** [comment]
Right now module extensions are only available in the desktop version of Outlook. I can't speak to the future plans for extensions.

While I was reviewing the README file for the sample I noticed a couple of problems that I need to fix, so thanks for that as well.

Thanks for your question,
Chuck
