### ISSUE TITLE
Outlook never displays the add-in

### ISSUE THREAD

**Issue by douglasware** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#6]
I cloned the repro and have not altered it. I am using Outlook 2016 16.0.6868.2062. The cert is trusted, I can see the site at https://localhost:8080 with no warnings indicating the cert is installed and npm/node both work. The app manifest uploaded fine and the add-in is marked active in my Office 365 account. 

Any ideas?

**Comment by douglasware** [comment]
@chbighammsft Hey Chuck! Is there anything you can suggest that I can do to get this working?

Thanks!

**Comment by chbighammsft** [comment]
Doug,

Looks like I have a fix for you. Try switching Outlook to online mode. Try this:
1.       On the file menu click Account Settings and then Account Settings…
2.       On the email tab, click the Exchange account, and then click Change…
3.       Under Offline Settings, clear the Use Cached Exchange Mode check box.
4.       Exit and restart Outlook.

Let me know if that solves it.

Chuck

**Comment by douglasware** [comment]
Hi Chuck,
Thanks so much! I tried that without success. This is what I see after turning off caching and restarting Outlook. (Same as before)

--Doug

[cid:image001.png@01D1B74C.84CE38C0]

**Comment by douglasware** [comment]
![image](https://cloud.githubusercontent.com/assets/8343795/15582990/b1f5a732-2341-11e6-9a3f-ce5682cde474.png)

**Comment by douglasware** [comment]
We worked this out over email. For reasons unknown, this only works if you are using a click to run version of Outlook from Office 365.

Thanks Chuck!

**Comment by Stefanosd** [comment]
I am unable to display the module in Outlook.  I followed all the steps in the example and even switched Outlook to online mode, per above suggestion.  Any help would be appreciated. @chbighammsft  @douglasware

**Comment by douglasware** [comment]
@Stefanosd I was only able to get it working using the 'Click to Run' version of Outlook that comes with Office 365. The 'regular' version seems to have issues at this point in time.

P.S. I closed this issue because I don't think it has anything to do with the sample itself... This is an Outlook bug.

**Comment by Stefanosd** [comment]
@douglasware I am running the 'Click to Run' version that comes with O365 and it's not working.  How can I confirm?
