### ISSUE TITLE
Unable to display the module sample in Outlook

### ISSUE THREAD

**Issue by Stefanosd** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#7]
I am unable to display the module in Outlook. I followed all the steps in the example and even switched Outlook to online mode, per above suggestion. Any help would be appreciated. @chbighammsft

**Comment by appalliance** [comment]
Did you ever get this working? You need to make sure the certificate is place in the "Trusted Root Certification Authorities" store.
