### ISSUE TITLE
Ribbon buttons disabled in Outlook Module sample

### ISSUE THREAD

**Issue by Stefanosd** [OfficeDev/Outlook-Add-in-JavaScript-ModuleExtension#8]
I modified the manifest file to create 3 groups within the Ribbon with a few buttons in each group.  The ribbons displays as I would expect, however the buttons are all disabled (greyed-out) .  Any thoughts as to what would cause this?

**Comment by chbighammsft** [comment]
Hey Stefano,

I’ve been sick and I’ve been buried in getting ready for a demo for another product. It will probably be early next week before I can get back to this.

Chuck
